version: "4"
services:
  api:
    build: 
      context: .
    container_name: nodejs-test
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
